test:
	go test -v ./...

test-integration:
	go test -v ./internal/integration_test/...

test-coverage:
	go test -v -coverprofile coverage.out -coverpkg=./internal/... ./...
	go tool cover -html=coverage.out

vul-check:
	govulncheck ./...