// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"mini-redis-go/internal/app"
	"mini-redis-go/internal/service/server"
)

// Injectors from wire.go:

func InitializeServer() *app.ServerApp {
	serverConfig := GetServerConfig()
	iServer := server.NewServerService(serverConfig)
	serverApp := app.NewServerApp(iServer)
	return serverApp
}
