// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/chantapat.t/GolandProjects/mini-redis-go/internal/service/server/core/broker_service.go

// Package mock_core is a generated GoMock package.
package mock

import (
	net "net"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBrokerService is a mock of BrokerService interface.
type MockBrokerService struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerServiceMockRecorder
}

// MockBrokerServiceMockRecorder is the mock recorder for MockBrokerService.
type MockBrokerServiceMockRecorder struct {
	mock *MockBrokerService
}

// NewMockBrokerService creates a new mock instance.
func NewMockBrokerService(ctrl *gomock.Controller) *MockBrokerService {
	mock := &MockBrokerService{ctrl: ctrl}
	mock.recorder = &MockBrokerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerService) EXPECT() *MockBrokerServiceMockRecorder {
	return m.recorder
}

// GetTopicFromConnection mocks base method.
func (m *MockBrokerService) GetTopicFromConnection(conn net.Conn) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicFromConnection", conn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTopicFromConnection indicates an expected call of GetTopicFromConnection.
func (mr *MockBrokerServiceMockRecorder) GetTopicFromConnection(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicFromConnection", reflect.TypeOf((*MockBrokerService)(nil).GetTopicFromConnection), conn)
}

// IsSubscriptionConnection mocks base method.
func (m *MockBrokerService) IsSubscriptionConnection(arg0 net.Conn) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSubscriptionConnection", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSubscriptionConnection indicates an expected call of IsSubscriptionConnection.
func (mr *MockBrokerServiceMockRecorder) IsSubscriptionConnection(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSubscriptionConnection", reflect.TypeOf((*MockBrokerService)(nil).IsSubscriptionConnection), arg0)
}

// Publish mocks base method.
func (m *MockBrokerService) Publish(conn net.Conn, topic, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", conn, topic, message)
}

// Publish indicates an expected call of Publish.
func (mr *MockBrokerServiceMockRecorder) Publish(conn, topic, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBrokerService)(nil).Publish), conn, topic, message)
}

// Subscribe mocks base method.
func (m *MockBrokerService) Subscribe(conn net.Conn, topic string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", conn, topic)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockBrokerServiceMockRecorder) Subscribe(conn, topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockBrokerService)(nil).Subscribe), conn, topic)
}

// Unsubscribe mocks base method.
func (m *MockBrokerService) Unsubscribe(conn net.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", conn)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockBrokerServiceMockRecorder) Unsubscribe(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockBrokerService)(nil).Unsubscribe), conn)
}
